[package]
name = "msg_queue"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-postgres = "0.7"
chrono = "0.4"
postgres-types = "0.2"
env_logger = "0.10"
